### ISSUE TITLE
	ptrClassicFrameLayout.setLoadMoreEnable(true) 设置加载更多报以下错误

### ISSUE THREAD

**Issue by qiufengyun** [Chanven/CommonPullToRefresh#52]
RecommendAdapter cannot be cast to com.chanven.lib.cptr.recyclerview.RecyclerAdapterWithHF

at com.chanven.lib.cptr.loadmore.RecyclerViewHandler.handleSetAdapter(RecyclerViewHandler.java:18)
                                                                                   at com.chanven.lib.cptr.PtrFrameLayout.setLoadMoreEnable(PtrFrameLayout.java:1073)

**Comment by lwklwc** [comment]
同样问题。。。

**Comment by zhiyou007** [comment]
我也是，用的通用ADAPTER，看DEMO，还有要做个中间adapter，感觉怪怪的
