### ISSUE TITLE
使用RecyclerView 加载到第二页后，再去拉下刷新(同时向下滚动)，报异常！

### ISSUE THREAD

**Issue by super-hu** [Chanven/CommonPullToRefresh#6]
java.lang.IndexOutOfBoundsException: Inconsistency detected. Invalid item position 4(offset:4).state:11
                                                                  at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:4405)
                                                                  at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:4363)
                                                                  at android.support.v7.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:1961)
                                                                  at android.support.v7.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1370)
                                                                  at android.support.v7.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1333)
                                                                  at android.support.v7.widget.LinearLayoutManager.scrollBy(LinearLayoutManager.java:1161)
                                                                  at android.support.v7.widget.LinearLayoutManager.scrollVerticallyBy(LinearLayoutManager.java:1018)
                                                                  at android.support.v7.widget.RecyclerView$ViewFlinger.run(RecyclerView.java:3807)
                                                                  at android.view.Choreographer$CallbackRecord.run(Choreographer.java:780)
                                                                  at android.view.Choreographer.doCallbacks(Choreographer.java:593)
                                                                  at android.view.Choreographer.doFrame(Choreographer.java:561)
                                                                  at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:766)
                                                                  at android.os.Handler.handleCallback(Handler.java:733)
                                                                  at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                  at android.os.Looper.loop(Looper.java:136)
                                                                  at android.app.ActivityThread.main(ActivityThread.java:5314)
                                                                  at java.lang.reflect.Method.invokeNative(Native Method)
                                                                  at java.lang.reflect.Method.invoke(Method.java:515)
                                                                  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:864)
                                                                  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:680)
                                                                  at dalvik.system.NativeStart.main(Native Method)

**Comment by heart2016** [comment]
请问 这个问题你解决了吗  我也遇到这个问题
